{
  "data": {
    "viewer": {
      "repositories": {
        "pageInfo": {
          "hasNextPage": false,
          "endCursor": "Y3Vyc29yOnYyOpHOHzqyqQ=="
        },
        "nodes": [
          {
            "name": "Gbraga30",
            "releases": {
              "totalCount": 0,
              "nodes": []
            }
          },
          {
            "name": "ExerciciosHtml",
            "releases": {
              "totalCount": 0,
              "nodes": []
            }
          },
          {
            "name": "Exerc-os-Frontend",
            "releases": {
              "totalCount": 0,
              "nodes": []
            }
          },
          {
            "name": "keras",
            "releases": {
              "totalCount": 0,
              "nodes": []
            }
          }
